version: '3.8'

services:
  dsv:
    image: rdnsx/docker-swarm-visualizer
    deploy:
      replicas: 1
    ports:
      - "8688:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
